name: Python application

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          pip install --upgrade pyinstaller
          pip install pyinstaller-versionfile
          curl -L https://github.com/upx/upx/releases/download/v4.2.4/upx-4.2.4-amd64_linux.tar.xz | tar xJf - -C /tmp
          mv /tmp/upx-4.2.4-amd64_linux /tmp/upx
      - name: Build binary
        run: |
          pyinstaller --clean --noconfirm --onefile --nowindow --distpath dist/ --workpath /tmp --upx-dir /tmp src/CxOneCli.py
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        run: >-
          gh release create ${{ github.ref_name }} ${{ github.workspace }}/dist/* --generate-notes --title "Version ${{ github.ref_name }}"
