name: Python application

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Package Application
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: src
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: src/dist/linux/*
        token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
